<?php
/**
 * @author    Sutunam
 * @copyright Copyright (c) 2024 Sutunam (http://www.sutunam.com/)
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\AbstractProduct;
use Magento\Framework\Escaper;
use Sutunam\LinkedProduct\Model\Config as ConfigData;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
// phpcs:disable Generic.Files.LineLength.TooLong

/** @var AbstractProduct $block */
/** @var Escaper $escaper */

/** @var ConfigData $configData */
$configData = $this->helper(ConfigData::class);

/** @var Magento\Catalog\Model\Product $product */
$product = $block->getData('product');

if (!$product) {
    return;
}

$attributeToLink = $product->getData('attribute_to_link');

if (!$attributeToLink) {
    return;
}

$currentProduct = $block->getCurrentProduct();
$isFirstProduct = $currentProduct->getId() && $currentProduct->getId() === $product->getId();

$showAttributeText = $configData->isShowAttributeText();

$showStockStatusText = $block->getData('show_stock_status_text');
$imageDisplayArea = $block->getData('image_display_area');
$imageCustomAttributes = $product->getData('image_custom_attributes')
    ?? $block->getData('image_custom_attributes')
    ?? [];
?>
<div id="product-linked-item_<?= /* @noEscape */ $product->getId() ?>" class="product-item">
    <a
        href="<?= $escaper->escapeUrl($block->getProductUrl($product)) ?>"
        class="product-image <?= $isFirstProduct ? 'product-image--active' : '' ?>"
    >
        <?= $block->getImage($product, $imageDisplayArea)
            ->setTemplate('Sutunam_LinkedProduct::product/linked/image.phtml')
            ->setData('custom_attributes', $imageCustomAttributes)
            ->setProductId($product->getId())
            ->toHtml(); ?>
    </a>
    <div class="product-info">
        <div class="product-attribute">
            <?php if (!$product->getIsSalable()): ?>
                <span class="product-saleable"></span>
            <?php endif; ?>

            <?php if ($showAttributeText): ?>
                <span class="product-attribute-text <?= !$product->getIsSalable() ? 'product-attribute-text--disable' : '' ?>">
                    <?= $escaper->escapeHtml($product->getAttributeText($attributeToLink)) ?>
                </span>
            <?php endif; ?>
        </div>
    </div>
</div>
